version: '3.8'
services:
  canvas_sketch:
    container_name: sketch
    image: pdpp/art_js:latest
    user: "root"
    ports:
      - "9966:9966"
    restart: always
    networks:
      - artnet
    volumes:
      - ./canvas:/canvas
    command: ["node", "/canvas", "sketch.js"]

networks:
  artnet:
    external: true
